apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecommerce.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
  BACKEND_URL: "http://{{ include "ecommerce.fullname" . }}-backend:{{ .Values.backend.service.port }}"
  MYSQL_HOST: "{{ include "ecommerce.fullname" . }}-mysql"
  MYSQL_PORT: "{{ .Values.mysql.service.port }}"
