apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ b64enc "rootpassword" }}
  MYSQL_PASSWORD: {{ b64enc "dbpassword" }}
  MYSQL_USER: {{ b64enc "ecommerce" }}
  MYSQL_DATABASE: {{ b64enc "ecommerce_db" }}
